### ISSUE TITLE
[Bug Report]: How to enable Shaders

### ISSUE THREAD

**Issue by L1v1dDX** [TeamAOF/Craftoria#106]
### Modpack Version

0.9.2

### Describe your issue.

Where can I find the option to enable shaders. I'm pretty sure the modpack even comes with Shaders already installed, but I don't know where to enable them.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

lividdx

**Comment by Kazuhiko-Gushiken** [comment]
`Esc` -> `Options...` -> `Video Settings...` -> `Shader Packs...`

Click on the one you want and press `Apply`.

**Comment by ImAK9** [comment]
Either update to 1.0.0 or if wanting to stay on 0.9.2 you'll have to remove Embeddium and add Sodium & Iris.
