### ISSUE TITLE
[Bug Report]: Extremely big log file (400MB in ~40 min)

### ISSUE THREAD

**Issue by nonFab** [TeamAOF/Craftoria#108]
### Modpack Version

1.0.0

### Describe your issue.

Log was normal with some warnings, but after ~2 hours the error `[Render thread/INFO] [mojang/GlDebug]: OpenGL debug message: id=1282, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION error generated. No active program.'` filled the log.

### Latest Log

https://gist.github.com/nonFab/838c6a23d69f2b4bf77be71ee99f0aaa

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by nonFab** [comment]
Also, no crashes. Game was working fine.

**Comment by ImAK9** [comment]
Fixed in newer versions
