### ISSUE TITLE
[Bug Report]: Hostile Neural Networks Deep Learner doesn't go into Curio slots (Even though it still registers its slot)

### ISSUE THREAD

**Issue by justsvenja** [TeamAOF/Craftoria#109]
### Modpack Version

1.0.0

### Describe your issue.

The Deep Learner from the Mod Hostile Neural Network won't go into the coresponding curious slot slot.
Tried it with Shift Clicking and In-Hand Right click.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

justsvenja

**Comment by WhitePhant0m** [comment]
https://github.com/Shadows-of-Fire/Hostile-Neural-Networks/issues/61
Dev of the mod doesn't seem interested in supporting either of the Curio forks for now,
will have to wait and see if they choose to support Curios again, or if they swap to Accessories.
