### ISSUE TITLE
[Bug Report]: Mekanism has no steel recipe?

### ISSUE THREAD

**Issue by SirWoofie** [TeamAOF/Craftoria#11]
### Modpack Version

0.0.9

### Describe your issue.

The Metallurgic Infuser from Mekanism does not have a recipe for steel. This prevents progression in Mekanism until you obtain steel through Modern Industrialization, the only other mod with a steel recipe.

### Have you modified the modpack?

Yes

### User Modifications

Disabled ToolBelt and FancyMenu

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by WhitePhant0m** [comment]
Already fixed in 0.0.11

**Comment by SirWoofie** [comment]
Fantastic, thanks! I had just updated the pack today so I hadn't thought to check if another update was released today.
