### ISSUE TITLE
[Bug Report]: Crashing on first startup

### ISSUE THREAD

**Issue by carstorm** [TeamAOF/Craftoria#111]
### Modpack Version

1.1.0

### Describe your issue.

Trying to launch server for the 1st time it keeps crashing. No crash report is made but will share log file.

### Latest Log

https://gist.github.com/carstorm/dd098f466d200b7db25b10ee92f34df9

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by ImAK9** [comment]
1.21 requires Java 21
