### ISSUE TITLE
[Bug Report]: Can't use resource packs anymore

### ISSUE THREAD

**Issue by ElijahKujo** [TeamAOF/Craftoria#121]
### Modpack Version

1.2.0

### Describe your issue.

I updated the pack (I am unsure what version I had before) and now I cannot move resource packs around in the menu. I have to use a certain arachnophobia resource pack as the more realistic ones added by the resource packs already in the modpack trigger me. Now I cannot use it anymore as it is forced to the bottom of the list, so it gets overridden by all the other packs, and I can't remove the other packs either. I do not know where the packs are stored or I'd go edit them to remove the spider models or flatout delete them from the game myself until I find another fix. 
I want to add this happens even on a fresh save and a fresh install of the modpack with no prior not up to date saves

### Crash Report

N/A

### Have you modified the modpack?

Yes

### User Modifications

https://www.curseforge.com/minecraft/texture-packs/arachnophobia

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

N/A

**Comment by ImAK9** [comment]
They're located in config/paxi/resources, delete as ya choose

**Comment by ElijahKujo** [comment]
> They're located in config/paxi/resourcepacks, delete as ya choose

Ty for telling me where they're stored! I'd still think this shouldn't be a thing as it is way more confusing than the way the game already handles resource packs.

**Comment by ImAK9** [comment]
I'd love to do it the vanilla way if resourcepack loading order wasnt such a pain, I'll see what I can do tho

**Comment by ray73864** [comment]
Glad I came here and found this issue, as I was having trouble figuring out how to go back to the default minecraft resource pack.

Went into the config/paxi/resourcepacks folder and deleted every single one of them, as I didn't want any of them.
