### ISSUE TITLE
[Bug Report]: Lignite Coal cannot be used in Coke Oven

### ISSUE THREAD

**Issue by ImAK9** [TeamAOF/Craftoria#126]
### Modpack Version

1.2.0

### Describe your issue.

Lignite Coal cannot be used in Coke Oven

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by WhitePhant0m** [comment]
Not a bug ya goober. MI doesn't add such recipe.

**Comment by ImAK9** [comment]
Rude
