### ISSUE TITLE
[Bug Report]: Nearly all Theurgy recipes broken 

### ISSUE THREAD

**Issue by amahlaka** [TeamAOF/Craftoria#13]
### Modpack Version

0.0.11

### Describe your issue.

Theurgy mod's recipies are no longer loaded in the game when using the modpack, out of many different recipes for Alchemical sulfurs of different kinds, only one of the recipes is loaded: Alchemical Sulfur of Wheat.

This seems to be related to the tags of items that are being messed with by the kubejs scripts, as
when loading the mod with just the same mods as the modpack, the recipies load just fine, but when including the kubejs folder 
 from the modpack, the issue emerges.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

amahlaka

**Comment by ImAK9** [comment]
Fixed in 0.0.12
