### ISSUE TITLE
[Bug Report]: Huge FPS drop

### ISSUE THREAD

**Issue by de4dcowboy** [TeamAOF/Craftoria#131]
### Modpack Version

1.2.0

### Describe your issue.

game was running fine over 120fps with unbound shaders. i died, collected my items and was chased by a swarm of zombies. there was a weather change and suddenly my frames have dropped to around 15 to 20fps with massive stuttering. didn't encounter any problems and cant seem to figure out whether it is an item or something else that has caused the issue. Restarting, reloading shaders etc is not fixing the issue and im stuck with very low frames. 

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

de4dcowboy

**Comment by ImAK9** [comment]
It's because of the rain throwing GL errors. Could you try updating Sodium & Iris and see if the issue persists

**Comment by de4dcowboy** [comment]
they are both updated and issue is still persisting for me unfortunately

**Comment by ImAK9** [comment]
This is an issue with Curseforge launcher instelf and how Overwolf implements their overlay. Either use the standalone version of Curseforge or a third-party launcher like Prism.
