### ISSUE TITLE
[Bug Report]: occutism quests abras commanding conjure

### ISSUE THREAD

**Issue by kads-e** [TeamAOF/Craftoria#132]
### Modpack Version

1.2 (eu server)

### Describe your issue.

![image](https://github.com/user-attachments/assets/fb7096d5-566a-4a44-aca7-1aaf6cf99615)
afrit line has the wrong circle, the right one is Abra's open conjure
(the one right now even needs afrit V:)
(the items are btw also correct, just the name of the quest not)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

infernal_pink

**Comment by ImAK9** [comment]
Fixed in 1.3.1
