### ISSUE TITLE
[Bug Report]: Croptopia utensils gets used up in recipes

### ISSUE THREAD

**Issue by fleeinkorean** [TeamAOF/Craftoria#137]
### Modpack Version

1.2.0

### Describe your issue.

When using the items like the cooking pot in recipes such as the one for Tofu, the cooking pot is used up with each craft. I doubt this is intended as using 5 iron every time you want to create one food item wouldn't be worth it at all. 

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by Linguardium** [comment]
fixed in 1.3.0.

**Comment by WhitePhant0m** [comment]
As said by Linguardium, it's already fixed in 1.3.0, please update.

**Comment by fleeinkorean** [comment]
I'm using the version on CurseForge, which was updated as recently as 2 days ago. Are the updates not being pushed out to that launcher?

**Comment by Linguardium** [comment]
https://www.curseforge.com/minecraft/modpacks/craftoria/files/5738664

if you need a link to the 1.3.0 version on curseforge
