### ISSUE TITLE
[Bug Report]: AE2 Guide not working corretly and crashing the game

### ISSUE THREAD

**Issue by Blackouto000** [TeamAOF/Craftoria#138]
### Modpack Version

1.3.0

### Describe your issue.

When holding G or right clicking the guide, the menu won't open at all, it opens if you hold G on the guide itself, but if change the tab, the game freezes and then crashes.

### Crash Report

https://mclo.gs/X79mc2M

### Latest Log

https://mclo.gs/yUmsvrw

### Have you modified the modpack?

Yes

### User Modifications

Only 3 mods were added, Item Highlighter, Puzzles Lib and Pick Up Notifier, which are inconsequential, as this bug happened even without them.

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by RoToN4iK** [comment]
on fresh install also have this crash

**Comment by ImAK9** [comment]
Update to 1.3.1
