### ISSUE TITLE
Automatic Refined obsidian with AE2

### ISSUE THREAD

**Issue by LeonardoSantan** [TeamAOF/Craftoria#139]
### Describe your suggestion

When trying to automatically craft refined obsidian bars through AE2, it is not possible to create osmium gas through the available machines. The “item to chemical” suggestion is to use the metallurgical infuser, but it doesn't receive osmium because it's used in recipes, and other machines don't accept output. I think it's necessary to add another mod to make it possible to process osmium into liquid.

### Why would you like this added/changed?

Possible solutions would be to change a craft, or add a specific craft via another mod to generate osmium gas for the machines.

**Comment by WhitePhant0m** [comment]
You're using the wrong machine, you're supposed to use osmium compressor, not metallurgic infuser, for the bars.

**Comment by LeonardoSantan** [comment]
What exactly should I do with the machine in question?
It doesn't accept osmium inputs sent via the applied pattern provider, which makes it impossible to automate the craft in question.
With other mekanism crafts in which the metallurgical infuser is used to create the gas (restone, diamond) and thus create the crafts (alloys in general), there should be the possibility of creating osmium gas for the automation in question.

**Comment by Linguardium** [comment]
mekanism machines you have to configure the sides to what slot they allow it to fill.

**Comment by LeonardoSantan** [comment]
The machine does not accept Osmiun and obsidian powder. The machine even has its own configuration for the gases, but it does not make the proper entries for the items in question, making automation impossible:
Image of the machine containing the obsidian dust:
![image](https://github.com/user-attachments/assets/4dca6f0b-f2a7-46e1-944f-f88350067658)

Hopper containing osmium indicating entry of items from the top of the machine:
![image](https://github.com/user-attachments/assets/22ab1fb5-3869-4226-987e-e9ed11f24343)

Chemicals” input configured for the top of the equipment to enter from the hopper:
![image](https://github.com/user-attachments/assets/9e6ee08c-7f8e-4a7c-b1c9-48e6061dda94)

The machine does not accept items in the input, unless it is made from gas.
In the example below, I use a chemical tank containing osmium, entering it through a pressurized tube of the same type.
![image](https://github.com/user-attachments/assets/0d1fb8f3-1c70-4ac6-8ee5-d446cbd8bfc6)

However, when trying to review the possible ways of generating the chemical in question, it is only possible to do it from the metalurgy infuser, otherwise it is indicated that through the purification chamber, osmium compressor and the chemical injection chamber, but both have the criticism that it is not possible to eject the chemical in question.
![image](https://github.com/user-attachments/assets/f766c141-724b-4734-b9dc-b1ae28def657)



So I repeat... is there another way to automate the craft in question? Without a change to the craft or the possibility of creating the chemical by a machine, I don't see it.

**Comment by Linguardium** [comment]
slot at bottom is yellow
slot on bottom is item
items settings are in the item tab at the top left
set the top slot to yellow to allow inputting into the slot

**Comment by LeonardoSantan** [comment]
Thanks for the almost immediate feedback. I was giving up on using the automation in question...
Using the “extra” input slot worked.
Thank you very much!!!
