### ISSUE TITLE
[Bug Report]: mekanism quest line

### ISSUE THREAD

**Issue by xxVintersorgxx** [TeamAOF/Craftoria#140]
### Modpack Version

1.3.1

### Describe your issue.

Unable to complete mekanism ore processing quest for crusher and dirty ore

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by SubordinalBlue** [comment]
Did you complete Purifying first?

It's a dependency, because crushing on it's own does not raise the multiple of produced ore... Purifying and Crushing have to go together to make the next tier of ore processing.

**Comment by xxVintersorgxx** [comment]
Solved it.  Used to working left to right.. didn't realize i needed to get all the things on the right of purification

**Comment by SubordinalBlue** [comment]
Aye, it is a little unusual quest chapter... it's setup so the flow of the dependency lines is the same as the 'flow' of ore and supporting substances in actual ore processing.

The ore quests, that have tier titles, are the entry points that allow completing building the lower tiers first, so one doesn't have to start by building the most advanced parts of ore processing.

I hope you find it satisfying to complete! Cheers.
