### ISSUE TITLE
[Bug Report]: 

### ISSUE THREAD

**Issue by MeekymanMC** [TeamAOF/Craftoria#141]
### Modpack Version

1.3.1

### Describe your issue.

Upon picking up my grave all of the items in my baubles inventory dissapeared including my artifacts and a diamond backpack full of items - Craftoria EU server

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

.meekyman.

**Comment by ImAK9** [comment]
As you've also reported this on Discord, I'll help you there.
