### ISSUE TITLE
[Bug Report]: Cosmetic Accessories Can't Be Hidden On Player Model

### ISSUE THREAD

**Issue by ItsSchmudt** [TeamAOF/Craftoria#142]
### Modpack Version

1.3.1

### Describe your issue.

When disabling certain accessories on my character, clicking the "hide" button disables the overlay for EMI items mod instead. It's annoying because I don't want every accessory on my character at every given moment. I tried digging into the settings to see if I could fix the issue, but to no avail, I had no such luck. A fix to this issue would be much appreciated by the whole community. Thank you

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

schm#schm

**Comment by ImAK9** [comment]
Fixed in 1.3.2, update your pack
