### ISSUE TITLE
[Bug Report]: Game Crashed On Start Up After Updating Mods And Neoforge Version

### ISSUE THREAD

**Issue by ItsSchmudt** [TeamAOF/Craftoria#143]
### Modpack Version

1.3.2

### Describe your issue.

After updating all of my mods to the latest version, when launching the game I was met with a message stating "Outdated Neoforge version for the Apothic mods" something along those lines. I went back and updated NeoForge to the latest which was 21.1.61, and now on the startup of the mod pack, I am met with a crash error saying "The game crashed whilst bootstrap
Error: java.lang.RuntimeException: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered" 

### Crash Report

The game crashed whilst bootstrap Error: java.lang.RuntimeException: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

schm#schm

**Comment by ImAK9** [comment]
Dont update mods... .60 added the Attribute Formatting API which is gonna break a thing or two.

**Comment by HeatherComputer** [comment]
Updating mods is never something the average player should do, leave that to the pack devs unless there's some major security flaw or similar.
