### ISSUE TITLE
[Bug Report]: Cosmetic Armor Reworked doesn't overlay armor

### ISSUE THREAD

**Issue by Jap00** [TeamAOF/Craftoria#144]
### Modpack Version

1.3.2

### Describe your issue.

Issue is not present in 1.3.1.
Since 1.3.2 any armor placed in the Cosmetic Armor Reworked slots (open inventory, click armor icon, extra cosmetic armor slots appear to the right) doesn't actually show.

Already contacted the Curios API Continuation dev since their mod got updated 2 days ago where they fixed an issue where the Visiblility button wasn't working for curios and thought maybe that broke it, but that's not the case (MC instance with just Curios and the CAR mod have no issues)
Unsure which mod/update caused this as of now.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by ImAK9** [comment]
It’s a bug with Transmog.
