### ISSUE TITLE
[Bug Report]: Game crashes when drinking Liquid Meat

### ISSUE THREAD

**Issue by fleeinkorean** [TeamAOF/Craftoria#146]
### Modpack Version

1.3.2

### Describe your issue.

When attempting to drink Liquid Meat from a source block placed in the world with a Straw, crashing occurs. Both items are from Industrial Foregoing.

### Crash Report

https://gist.github.com/fleeinkorean/5fb0e2c4b1424eb2898d6783feacf4db

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by Linguardium** [comment]
reported to IF https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/issues/1478

**Comment by Linguardium** [comment]
Issue fixed in dev. next IF release should be fixed
