### ISSUE TITLE
[Bug Report]: 

### ISSUE THREAD

**Issue by Crayola-oss** [TeamAOF/Craftoria#147]
### Modpack Version

1.3.2

### Describe your issue.

Any time I try loading the mod pack, I'm hit with exit code 1, and the midpack crashes. I've loaded other mod packs, so I know it's not my computer. I'm assuming it's just a simple fix I'm missing.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

.crayolavirus

**Comment by Linguardium** [comment]
not a craftoria modpack issue. open a support thread on the discord for quicker support
