### ISSUE TITLE
[Bug Report]: Crash on AE2 guide tab opening

### ISSUE THREAD

**Issue by Thorres** [TeamAOF/Craftoria#150]
### Modpack Version

1.21.1

### Describe your issue.

When I try to access the "AE2 Mechanics -> Certus Growth" tab in the AE2 guide I get the following crash:

The game crashed whilst mouseclicked event handler
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.core.RegistryAccess.lookup(net.minecraft.resources.ResourceKey)" because the return value of "net.minecraft.world.level.Level.registryAccess()" is null

### Crash Report

https://gist.github.com/Thorres/6b6b1ea3178c205b097329f6cdc01eb3

### Latest Log

https://gist.github.com/Thorres/2c8da3f120079c0ee37bef7f0ca9c129

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by WhitePhant0m** [comment]
Update the pack to 1.3.1+, also, 1.21.1 isn't the pack version.
