### ISSUE TITLE
[Bug Report]: Server setup

### ISSUE THREAD

**Issue by StonyRyan** [TeamAOF/Craftoria#151]
### Modpack Version

1.3.2

### Describe your issue.

I am trying to setup the server with the server setup pack posted on curse forge, It has not been working at all I tried getting help from multiple discord servers the end result is me being told that the publishers released a broken server pack Im not sure what to do really.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

StonyRyan

**Comment by Linguardium** [comment]
I can assure you the pack is not broken. i have freshly installed the server pack multiple times on multiple computers and operating systems

**Comment by Linguardium** [comment]
just read your discord. you keep using the wrong java version

**Comment by StonyRyan** [comment]
I even tried it with Universalator too, It automatically installed the version for me after I messed up multiple times, I'm not sure what else I can do
![aaaaa](https://github.com/user-attachments/assets/8b801579-055b-4d19-89b0-729dba0b365a)

**Comment by SubordinalBlue** [comment]
You seem to have the wrong version of Java installed, mate.

https://discord.com/channels/570630340075454474/1289030857004290101
