### ISSUE TITLE
[Bug Report]: Garlic just dupes when using it with cutting board

### ISSUE THREAD

**Issue by RealFoxass** [TeamAOF/Craftoria#155]
### Modpack Version

1.4.0

### Describe your issue.

When using garlic on a cutting board instead of it giving you garlic cloves it now just gives you 5 more garlic instead
![Screenshot 2024-09-28 033614](https://github.com/user-attachments/assets/21198f90-6a06-4e21-abe6-530ce19c64d3)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

foxhendrixx

**Comment by ImAK9** [comment]
Fixed in 1.4.1
