### ISSUE TITLE
[Bug Report]: Quest Book Mekanism 

### ISSUE THREAD

**Issue by VNakax** [TeamAOF/Craftoria#156]
### Modpack Version

1.3.0

### Describe your issue.

On the Mekanism quest path, the mission time for Chemestry has "No task" and "No Reward", and blocks the advance on mekanism quests since its a required task on the main line

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

vnaka

**Comment by VNakax** [comment]
updating to 1.4.0 made this quest complete(but not sure if in the way it was intended since i got another task completed - on AE2 - that i only had partial completion)

**Comment by Kazuhiko-Gushiken** [comment]
The original was a checkmark quest and it had been worded poorly for the information it was originally supposed to convey. I had attempted to fix that problem by adjusting the wording and making the quest optional, but I may have also broke the task. I believe the newest update fixes it to how it's supposed to be.

**Comment by Kazuhiko-Gushiken** [comment]
Fixed in Latest
