### ISSUE TITLE
[Bug Report]: macOS `.icns` outdated

### ISSUE THREAD

**Issue by DuroCodes** [TeamAOF/Craftoria#159]
### Modpack Version

1.4.1

### Describe your issue.

The old logo was appearing for macOS; I have updated it and attached a newer `.icns` file. Additionally, the old `.icns` was low-resolution, so that's also been fixed with the new `.icns` attached 😄

Apparently GitHub doesn't let you upload `.icns` files, so I have to zip it :(

[window_icon_mac.icns.zip](https://github.com/user-attachments/files/17198546/window_icon_mac.icns.zip)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

### Discord Username

_duro

**Comment by SubordinalBlue** [comment]
Good catch. Fixed with 038079e.
