### ISSUE TITLE
[Bug Report]: batch file cannot find or load main class

### ISSUE THREAD

**Issue by nathanwalters99** [TeamAOF/Craftoria#160]
### Modpack Version

1.4.1

### Describe your issue.

When running the 'startserver.bat' file I am getting the following error:
Error: Could not find or load main class @libraries.net.neoforged.neoforge.21.1.59.win_args.txt

I checked the 'Craftoria-Server-1.4.1\libraries\net\neoforged\neoforge\21.1.59' directory and could see the 'win_args.txt' file, so I am unsure why the batch is unable to find it

### Crash Report

NA

### Latest Log

NA

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by JakeyPrime** [comment]
+1 to this issue, but I'm having the same issue but with the Unix args library, rather than the windows one
`Could not find or load main class @libraries.net.neoforged.neoforge.21.1.59.unix_args.txt`

**Comment by SubordinalBlue** [comment]
Be sure java 21 is getting called when double clicking the .bat file.

Can check by running the command `java —version` in a cmd/powershell/terminal window.

**Comment by Trickelodean** [comment]
Updating to java 21 fixed the issue! Thanks

**Comment by WhitePhant0m** [comment]
That error is from not running it with java21, minecraft needs that java version since 1.21.
