### ISSUE TITLE
[Bug Report]: Easy Villagers is causing FPS drops

### ISSUE THREAD

**Issue by TatuTheTatu** [TeamAOF/Craftoria#161]
### Modpack Version

1.4.1

### Describe your issue.

Situations where the FPS drops:

  - When I search for the mod in JEI.
  - When any block from the mod is in the open inventory; it normalizes when the inventory is closed.
  - When any block from the mod is placed in the world. (In this situation, every time I get close to the blocks or look at them, the FPS drops.)

I'm playing at 60 FPS, and in all these situations, it drops to 0 for a few seconds and then returns to normal.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by Linguardium** [comment]
Easy Villagers was removed in a previous version 
https://github.com/TeamAOF/Craftoria/blob/main/changelogs/modlist_1.4.1.md
