### ISSUE TITLE
[Bug Report]: 

### ISSUE THREAD

**Issue by JamesTMNA** [TeamAOF/Craftoria#162]
### Modpack Version

1.4.1

### Describe your issue.

Error when installing server files locally after EULA agreement:

Error occurred during initialization of boot layer
java.lang.module.FindException: Error reading module: libraries\cpw\mods\securejarhandler\3.0.8\securejarhandler-3.0.8.jar
Caused by: java.lang.module.InvalidModuleDescriptorException: Unsupported major.minor version 65.0

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by WhitePhant0m** [comment]
As said above, use java21
