### ISSUE TITLE
[Bug Report]: No Iridium ore spawn in overworld

### ISSUE THREAD

**Issue by SMFDrummer** [TeamAOF/Craftoria#164]
### Modpack Version

1.3.2

### Describe your issue.

As title, iridium can only craft by small iridium dust, overworld has nothing about iridium ore, this bug causes I cannot going Modern Industralication's HV2Quantum way.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by SMFDrummer** [comment]
Is iridium ore only obtained by titanium drill? But EMI tips me about iridium ore that it can spawn at Y: -64 ~ 16 , everychunk has 10 ore vein and every vein has 1 ore. Is this a real bug? Or you guys changed the MI-mod ore spawn rule?
![image](https://github.com/user-attachments/assets/8a0c7304-6184-4d17-b3df-e24fcdc76618)

**Comment by SMFDrummer** [comment]
My Server is using official server-pack, client only install font fix and advanced-xray, but through I use xray I cannot find any iridium ore in overworld, mek-mining-machine yet.

**Comment by Kazuhiko-Gushiken** [comment]
@SMFDrummer 
The method to get Iridium is as follows:

-> Obtain Platinum Ore from Stainless Steel Drill
-> Macerate it down into Raw Platinum Ore
-> Mix with Sulfuric Acid in a Chemical Reactor
-> Use the Centrifuge to turn the Platinum Sulfuric Solution into Purified Platinum Sulfuric Solution and Iridium Tiny Dust
-> Turn 9 Iridium Tiny Dust into 1 Iridium Dust
-> Smelt Iridium Dust to make Iridium Ingot

This is the intended route BY the mod Modern Industrialization.
