### ISSUE TITLE
[Bug Report]: No Butcher Knife

### ISSUE THREAD

**Issue by AntoineMazoyer** [TeamAOF/Craftoria#168]
### Modpack Version

1.21.1

### Describe your issue.

Hi. I love the mod pack ! But recently i played in 1.21.1 and it's impossible to craft the butcher knife. Any idea ? And i've checked the kubejs file but the item don't appear. Thanks for the help.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by 800020h** [comment]
any knife should work in this pack

**Comment by Leonxilofin** [comment]
Yea, they disabled the butcher knife. You can use all the other knives to get tallow.  They just need to fix the quest description that tells you to craft the butcher knife

**Comment by WhitePhant0m** [comment]
1st,1.21.1 isn't the modpack version, that's the minecraft version
2nd, wasn't this fixed in 1.4.1? (except for the description still being a bit outdated, will fix for next update)

**Comment by ImAK9** [comment]
This was fixed in 1.4.1
