### ISSUE TITLE
[Mod Suggestion]: About Compressed Block

### ISSUE THREAD

**Issue by SMFDrummer** [TeamAOF/Craftoria#172]
### URL

https://legacy.curseforge.com/minecraft/modpacks/craftoria

### Why would you like this mod added?

Why Compressed Block cannot be replicated by MI-replicator? Is this a bug? Since all compressed blocks cannot be replicated, what is the purpose of this thing's existence? What was this thing designed for? Is it just to reduce the box occupancy? You should know that with QIO drivers, there is no need for boxes, and ME drivers are no longer necessary.

**Comment by WhitePhant0m** [comment]
For now they are mostly there to be able to save space if you don't have high capacity drives and such, but I do have plans for using them for some recipes.
