### ISSUE TITLE
[Mod Suggestion]: Dynamic FPS

### ISSUE THREAD

**Issue by nvkomata** [TeamAOF/Craftoria#173]
### URL

https://www.curseforge.com/minecraft/mc-mods/dynamic-fps

### Why would you like this mod added?

this mod allows for such while minecraft is out of focus:

- limit fps
- change sounds volume
- pause toast notifications

this would be a great addition for people that often tab out of the game or keep it in the background, i hope to see it mainlined in the modpack!

**Comment by Linguardium** [comment]
I have seen nothing but problems with dynamic fps. sometimes it determines the game is out of focus when it isnt and tanks fps and processing clientside while people are playing. It is not difficult to add it yourself if you dont have issues but with so many overlay applications conflicting, i would advise against it.

**Comment by nvkomata** [comment]
> I have seen nothing but problems with dynamic fps. sometimes it determines the game is out of focus when it isnt and tanks fps and processing clientside while people are playing. It is not difficult to add it yourself if you dont have issues but with so many overlay applications conflicting, i would advise against it.

that's a load of hooey

**Comment by Linguardium** [comment]
its a balance of potential problems for people who want to play a working, complete pack vs a QoL for some users. it makes more sense for large packs to avoid the risk of problems and let the players that want to add their desired clientside QoL mods themselves

**Comment by Leonxilofin** [comment]
Gonna agree with linguardium on this one. Players shouldn't have to remove a "possibly" problematic mod If it's known to have stability issues in the past. Even if it works great for a few players.. Personally I've never had a good experiance with it but my situation may be a bit different with a multiple monitor settup. Shouldn't be too difficult for you to add it yourself :)
