### ISSUE TITLE
Unable to launch a server

### ISSUE THREAD

**Issue by dooooot123** [TeamAOF/Craftoria#176]
Hello, I'm unable to get a server going. Not sure how to address this error on startup: Error: Could not find or load main class @libraries.net.neoforged.neoforge.21.1.59.win_args.txt. Please let me know how i can fix this. Thank you!

**Comment by SubordinalBlue** [comment]
First, be sure your using Java21.

**Comment by dooooot123** [comment]
wow that was it, im a little slow!!!11!!1! Thank you so much i was not aware of how it worked.
