### ISSUE TITLE
[Bug Report]: FPS drop while using shaders

### ISSUE THREAD

**Issue by MrKeplin** [TeamAOF/Craftoria#178]
### Modpack Version

1.4.1

### Describe your issue.

After around 20 / 30 minutes of gameplay, FPS will start to drop to 40 fps, while checking f3 for any clues, there... isnt... gpu % usage is at 30%, vsync is off, confirmed no fps limit and ram usage is at 60%. 

Shaders: complementary unbound + fix - high (default) profile. 
CPU: Ryzen 5 5600g 
GPU: AMD RX 6600
RAM: 32GB dual 
windows 11 i g. 

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

_keplin

**Comment by Linguardium** [comment]
if using the curseforge launcher, try a different launcher such as Prism Launcher

**Comment by SubordinalBlue** [comment]
Will add, for myself I see my allocation rate go a bit higher with shaders on, but gameplay is still smooth when using ZGC Generational.

Closing as stale; OP, feel free to reopen, or maybe better, seek further help on AOE discord... good peeps there.
