### ISSUE TITLE
Unix Server unix_args.txt not found

### ISSUE THREAD

**Issue by bluenby** [TeamAOF/Craftoria#181]
### Modpack Version

2.4.1

### Describe your issue.

[Server] INFO Error: Could not find or load main class @libraries.net.neoforged.neoforge.21.1.59.unix_args.txt

Using Voodoo servers, java 21, deleted and reinstalled the whole server from scratch to ensure it wasn't anything else. This is the only issue in common. There are no logs or crash reports as it isn't even getting to that point.

### Latest Log

https://gist.github.com/bluenby/43633212a7dc5f5adcc1d6e687b1b7bb

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

blunby

**Comment by Linguardium** [comment]
there should be a message above this. generally this error occurs when you are using java 8

**Comment by bluenby** [comment]
I have checked other errors on both Github and Discord, so unless Multicraft is lying to my face, which I checked that too, I am running this with Java 21.

**Comment by Linguardium** [comment]
add `    - "--show-version"` in the `  javaArgs:` section of the yaml

```
  javaArgs:
    - "-XX:+UseG1GC"
    - "--show-version"
```

**Comment by bluenby** [comment]
The server host seems to be running the serverstarter-2.4.1.jar with java 21, but the when the actual server jars are started, the ProcessBuilder calls java 8 instead of java 21.

**Comment by Linguardium** [comment]
if you know the path to the java executable, you can set it directly in the forced java path in the yaml

**Comment by SubordinalBlue** [comment]
Closing as stale/seems to be on hosting support. Feel free to re-open or—maybe better for this case—seek further advice on AOE discord.
