### ISSUE TITLE
[Bug Report]: Crashing when launching

### ISSUE THREAD

**Issue by Gogoms** [TeamAOF/Craftoria#182]
### Modpack Version

1.4.1

### Describe your issue.

When attempting to launch the game, it crashes instantly. No loading screen, no new window, just a few seconds of nothing then back to the launcher.

Tried it on both versions of curseforge, the overwolf and standalone. Tried a fresh install, tried repairing minecraft installation, and drivers should be up to date.

*ps: sorry for commenting on other thread, had github for less than a day and didn't know whether to make a new thread or not

### Crash Report

https://gist.github.com/Gogoms/3dd9d1569061ab45d20bc5743acb2cf1

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by Gogoms** [comment]
That solved it thank you, don't know why windows was telling me my drivers were up to date.

**Comment by NoahScior** [comment]
How did you fix this mine is saying drivers need an update but my drivers are updated?
