### ISSUE TITLE
[Bug Report]: Server Crash

### ISSUE THREAD

**Issue by Cebio** [TeamAOF/Craftoria#183]
### Modpack Version

1.5.0

### Describe your issue.

I just get this crash in the logs. Im new to the modded server community.

[crash-2024-10-12_02.17.00-fml.txt](https://github.com/user-attachments/files/17348034/crash-2024-10-12_02.17.00-fml.txt)

### Crash Report

https://gist.github.com/Cebio/cd6ee341ba4328cd1481219f77dce29c

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by ImAK9** [comment]
This should be reported to the Ars Additions mod

**Comment by Cebio** [comment]
Is this something that i should do?

**Comment by ImAK9** [comment]
If you're able to I'd appreciate it yeah.

**Comment by ImAK9** [comment]
Wait, try Java 21 first

**Comment by Cebio** [comment]
Its kinda frustrating that nearly everymodpack is giving another error when launching. I guess its me problem but i dont know how to solve each of them. Kinda regretting buying server for playing modded mc. Literally 3 days wasted in this with over 10 hours lol. Appreciating your help tho dont get me wrong.

**Comment by ImAK9** [comment]
Remove J23 from path in environmental variables

**Comment by Cebio** [comment]
Ok i removed J23 both from path and computer also checked java -version. Current is 21 but error is same

**Comment by Cebio** [comment]
[crash-2024-10-12_02.46.38-fml.txt](https://github.com/user-attachments/files/17348107/crash-2024-10-12_02.46.38-fml.txt)

**Comment by Linguardium** [comment]
your computer operating system language is likely turkish (or a similar non-english language) causing issues with some mods that are poorly designed

add ```-Duser.country=US``` and ```-Duser.language=en``` to your jvm args

**Comment by Cebio** [comment]
Ok now trying just in case, I can change my operating system language. Should i also try to uninstall java and install it again after operating system change?

**Comment by Linguardium** [comment]
nope, you either need to use the jvm arguments to make java thing you are using english or just set your operating system to english. 

Your java version is good

**Comment by Cebio** [comment]
THANK YOU, from the bottom of my heart! I wasted 3 days over 12 hours on this errors and it was driving me insane that i couldn't solve it in the end and getting help from github was my last try. This literally reminded me the first day of black myth wukong which literally had the same problem that boss was frozing in middle of combat and was not dying just because of operating system and region setted in Turkey. Never ever using my countries location or operating system language again. THANK YOU!

**Comment by Linguardium** [comment]
for your information, the mod dev has fixed their mod and the fix should be in the next release of ArsAdditions

**Comment by Cebio** [comment]
Yeah but also in other modpacks like allthemods10 it was both this mod and EnderIO was giving me a problem. So this literally solved every modpack for me too. Everything works perfect for now. I can rest a little thank you
