### ISSUE TITLE
[Bug Report]:  Error on loading world

### ISSUE THREAD

**Issue by homelesstaco** [TeamAOF/Craftoria#187]
### Modpack Version

1.4.1

### Describe your issue.

![error 1](https://github.com/user-attachments/assets/d7e2337c-7315-4015-8ab1-dac30abcd7ee)
When loading the world I get this error message. 

<img width="1634" alt="console error" src="https://github.com/user-attachments/assets/e5e86fe9-e811-4b68-a885-4966110b6fad">
This is what it it showing me in the console of the server.

I am not sure where to look to get this resolved. Thanks for any help 

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by SubordinalBlue** [comment]
You have a mismatch between pack versions of your client and the server you are trying to connect to.
