### ISSUE TITLE
[Bug Report]: Crash on Mod Loading

### ISSUE THREAD

**Issue by AksharLeo** [TeamAOF/Craftoria#193]
### Modpack Version

1.5.0

### Describe your issue.

![image](https://github.com/user-attachments/assets/a09e7b76-d8c6-4380-adff-81402a68f12d)

Crashes in the middle of loading all the mods, game runs fine if you set `earlyWindowControl = false` in fml.toml

CPU: Ryzen 7 5800H
GPU: Radeon RX 6600M

### Latest Log

https://gist.github.com/AksharLeo/ef270d883e0bb704b7ecc41ff71bc40b

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by SubordinalBlue** [comment]
You're using Java17; Craftoria, like any mudpack based on Minecraft 1.21, requires Java21.
