### ISSUE TITLE
[Bug Report]: Basalt Barrera biome generation 

### ISSUE THREAD

**Issue by yoyoyogurt** [TeamAOF/Craftoria#203]
### Modpack Version

1.5

### Describe your issue.

Basalt Barrera biome generation is relatively slow to generate. Unplayably slow for me. I have no problem with any generation, but everytime a new basalt barrera biome chunk generates it takes a literal minute.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by SubordinalBlue** [comment]
TY; BWG devs notified.
