### ISSUE TITLE
[Bug Report]: Server crash on start up

### ISSUE THREAD

**Issue by paolellagram** [TeamAOF/Craftoria#204]
### Modpack Version

1.5.0

### Describe your issue.

I'm trying to add the mod pack to my neo server and it's crashing when I start the server up. It hangs on a bootstrap call but also looks like it can't find some of the config files. I've attached the log and crash report. I was using Java 23 then saw another issue reported here where an author suggested to use Java 21. I tried that and still no luck, but 21 is what I still currently have installed. Thank you in advance!

[crash-2024-10-
[latest.log](https://github.com/user-attachments/files/17396922/latest.log)
16_09.46.12-fml.txt](https://github.com/user-attachments/files/17396919/crash-2024-10-16_09.46.12-fml.txt)

### Crash Report

https://github.com/user-attachments/files/17396919/crash-2024-10-16_09.46.12-fml.txt

### Latest Log

https://github.com/user-attachments/files/17396922/latest.log

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

paolellagram

**Comment by SubordinalBlue** [comment]
Java21 is right, but it looks like you have a new NeoForge than is specified for the latest pack version.
Yours -> NeoForge: 21.1.71
Craftoria 1.5.0 -> 21.1.66

Try the intended version…
…but also, be sure to install the server with the script, and yaml settings file, as shipped.

**Comment by paolellagram** [comment]
I don't think I follow what you mean by "be sure to install the server with the script, and yaml settings file, as shipped." Is there meant to be a script for creating the server in the Craftoria zip?

**Comment by paolellagram** [comment]
Ah I didn't realize there was a separate download for the server. Thanks so much!
