### ISSUE TITLE
.

### ISSUE THREAD

**Issue by ItsPows** [TeamAOF/Craftoria#209]

**Comment by ItsPows** [comment]
![image](https://github.com/user-attachments/assets/77ed6c5a-7b6c-43c5-a5af-6fd5f8fffba5)
![image](https://github.com/user-attachments/assets/cf6930b0-4d80-44d1-b43c-fffc5acb29a5)

**Comment by SubordinalBlue** [comment]
?

**Comment by moosetwin0** [comment]
!

**Comment by SubordinalBlue** [comment]
@ItsPows ... your posts in this issue are empty. Is there something you wanted to say?

**Comment by SubordinalBlue** [comment]
Closing as... an empty issue. xD
