### ISSUE TITLE
[Bug Report]: JDT Nightvision Upgrade doesn't work with Any of the existing shaders

### ISSUE THREAD

**Issue by Dragonex97** [TeamAOF/Craftoria#211]
### Modpack Version

1.5.0

### Describe your issue.

as the title says the JDT nightvision upgrade seems to not work with any of the existing shaderpacks it's pitch dark, but once you turn off the shaders it works fine (https://gyazo.com/48e7c44a7584098d773daaaa1b10fcee -shaders off) (https://gyazo.com/b4dd2877450cb32213b0d0112a4a959e -shaders on) as in the image links, its definetly visible the difference between on and off.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by SubordinalBlue** [comment]
Yes, that would best be filed as a feature request on JDT’s repo (or maybe even Iris)… many effects individual mods would like to do, do not work with shaders (as players think of them) in Minecraft.
JDT portals and goo transformations being more examples.
