### ISSUE TITLE
[Bug Report]: Constant Crashes

### ISSUE THREAD

**Issue by GridinVladimir** [TeamAOF/Craftoria#214]
### Modpack Version

1.5.0

### Describe your issue.

Hello. Game is randomly crashing while playing. Can't say what mod/interaction makes it crash. However Minecraft log does say that "There is insufficient memory for the Java Runtime Environment to continue". I've tried giving modpack more RAM (from 8GB, to 9, 10, even 12GB) and it did not help. Changing in-game quality and rendering settings did not do anything, crashes still occur.
My laptop specs are:
16 GB of RAM; Intel Core i7-12700H; NVIDIA GeForce RTX 3070 Laptop 8GB.
Maybe the problem is that Minecraft does not have enough memory? But I played modpacks that are much more modded than this, and it was just fine.

### Crash Report

https://gist.github.com/GridinVladimir/a7756be5d34174d3f6b5e2fddc45a7b7

### Latest Log

https://gist.github.com/GridinVladimir/10e385a60cb85079f814fb35ba6ce363

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by GridinVladimir** [comment]
Keep getting "There is insufficient memory for the Java Runtime Environment to continue." crashes. Sometimes just opening random loot chest is enough, other times chunk loading causes it. No idea why there is insufficient memory, I've tried giving it more, but error persists

**Comment by SubordinalBlue** [comment]
Do you have a crash report? The link labeled as such is another log.

**Comment by GridinVladimir** [comment]
> Do you have a crash report? The link labeled as such is another log.

my bad, copied the wrong file. what's crash report called? too much .log files, and not one that's outright called crash report.

**Comment by GridinVladimir** [comment]
hope this is the one: https://gist.github.com/GridinVladimir/ac7d56019eed3073edcc71d20ba46802

**Comment by SubordinalBlue** [comment]
Hmm.. this reads like your _system_ (Windows, the computer as a whole) is running out of memory to let java have what you've told it to use:
```
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 2080374784 bytes for G1 virtual space
# Possible reasons:
#   The system is out of physical RAM or swap space
#   The process is running with CompressedOops enabled, and the Java Heap may be blocking the growth of the native heap
# Possible solutions:
#   Reduce memory load on the system
#   Increase physical memory or swap space
#   Check if swap backing store is full
```

**Comment by SubordinalBlue** [comment]
And also try with giving the game just 8G, not 10: ```-Xmx10496m```.
It should run fine with 8GB. That's how I run it, even with Distant Horizons added.

**Comment by GridinVladimir** [comment]
> Hmm.. this reads like your _system_ (Windows, the computer as a whole) is running out of memory to let java have what you've told it to use:
> 
> ```
> # There is insufficient memory for the Java Runtime Environment to continue.
> # Native memory allocation (mmap) failed to map 2080374784 bytes for G1 virtual space
> # Possible reasons:
> #   The system is out of physical RAM or swap space
> #   The process is running with CompressedOops enabled, and the Java Heap may be blocking the growth of the native heap
> # Possible solutions:
> #   Reduce memory load on the system
> #   Increase physical memory or swap space
> #   Check if swap backing store is full
> ```
> 
> What happens after rebooting the computer and _not_ starting anything else but the game? (no browser, no steam, etc... for science sake ^^)

I did check that, after the reboot, resource monitor shows that I have around 4 gb of memory in use, even if I disable and exit out of all apps at the start. google results showed that apparently it's okay, because the system uses it, and when other apps require this memory, system gives it back, or something like that. I'll try 8GB again, thank you

**Comment by GridinVladimir** [comment]
After few days, crashes still persists. Happens completely randomly, and I am out of options already. I don't know if this is a modpack problem, or a problem with java on my pc, or even PC memory problem in general. Everytime it's the same error: "There is insufficient memory for the Java Runtime Environment to continue."

**Comment by Linguardium** [comment]
the underlying issue here is your computer itself is running out of ram. you dont have enough ram to run the things needed.

Memory: 4k page, system-wide physical 16108M (866M free)
TotalPageFile size 20204M (AvailPageFile size 776M)

you can see you have less than 1GB free space and have used nearly 20GB of swap (the super slow hard drive space the computer uses when it runs out of ram and you keep trying to use more)

You have allocated 10GB to heap.  heap is not the only memory java needs to use, it has stack and some other memory space as well. so ultimately you have allocated 14GB to java/minecraft. 

You only have 16GB _total_ on your computer. your computer also still requires ram to run applications, windows itself, and other things.  you should not allocate more than 6GB to the game with 16GB total system ram.

Additionally, since you are on a ram constrained system, i suggest not using ZGC (you aren't, this is just a note for people trying to help) as it is known to use more ram for its background GC processes.

Additionally Additionally, check your free ram before launching minecraft. you will want at least 10GB free when you have 6GB allocated before launching. be sure to close applications before opening minecraft.

**Comment by GridinVladimir** [comment]
> the underlying issue here is your computer itself is running out of ram. you dont have enough ram to run the things needed.
> 
> > Memory: 4k page, system-wide physical 16108M (866M free)
> > TotalPageFile size 20204M (AvailPageFile size 776M)
> 
> you can see you have less than 1GB free space and have used nearly 20GB of swap (the super slow hard drive space the computer uses when it runs out of ram and you keep trying to use more)
> 
> You have allocated 10GB to heap. heap is not the only memory java needs to use, it has stack and some other memory space as well. so ultimately you have allocated 14GB to java/minecraft.
> 
> You only have 16GB _total_ on your computer. your computer also still requires ram to run applications, windows itself, and other things. you should not allocate more than 6GB to the game with 16GB total system ram.
> 
> Additionally, since you are on a ram constrained system, i suggest not using ZGC (you aren't, this is just a note for people trying to help) as it is known to use more ram for its background GC processes.
> 
> Additionally Additionally, check your free ram before launching minecraft. you will want at least 10GB free when you have 6GB allocated before launching. be sure to close applications before opening minecraft.

I see, I understand better now. Thank you very much
