### ISSUE TITLE
[Bug Report]: Disconnect on loading world

### ISSUE THREAD

**Issue by moosetwin0** [TeamAOF/Craftoria#215]
### Modpack Version

1.5.0

### Describe your issue.

When trying to load my world, after the message 'Loading terrain...', it exits the world with the messages 'Connection Lost' and 'Disconnected'.

### Crash Report

N/A

### Latest Log

https://gist.github.com/moosetwin0/306dd97e16ad7911972f1a6ecd89e413

### Have you modified the modpack?

No

### User Modifications

N/A

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

N/A

**Comment by SubordinalBlue** [comment]
Whole lotta GL errors at the end of that log, and from looking at the top, it seems to be using integrated Intel graphics. It might not be happy about that.

Is there a crash report, maybe?

**Comment by moosetwin0** [comment]
> Is there a crash report, maybe?

Nope, it just disconnects from the world.

**Comment by moosetwin0** [comment]
Embarrassingly enough, I didn't think to restart the client until just now, and that worked. I'll send the new log in a moment in case you want to compare them or something.

**Comment by moosetwin0** [comment]
Here's the working log: https://gist.github.com/moosetwin0/81a62df4a58789368890bb8880ae9f81
