### ISSUE TITLE
Change Mekanism: Ore Processing to require raw ores instead of ore blocks

### ISSUE THREAD

**Issue by moosetwin0** [TeamAOF/Craftoria#217]
### Describe your suggestion

Change the valid items for the 'Tier %, 1:%' quests from ore blocks to raw ores.
E.g. Change Iron Ore to Raw Iron.

### Why would you like this added/changed?

Silk Touch is required to obtain ore blocks, whereas most people who are starting out with ore processing don't have Silk Touch yet.

**Comment by SubordinalBlue** [comment]
Yes... but that's the point. To get best results from ore processing—the point of ore processing—you need to feed in the silk touched ores.

**Comment by SubordinalBlue** [comment]
I should add, the pack has several ways to get silk touch; to name two tech methods: steam mining drills and mining gadgets with the silk touch upgrade.
