### ISSUE TITLE
[Bug Report]: World closes apon opening backpack

### ISSUE THREAD

**Issue by moosetwin0** [TeamAOF/Craftoria#219]
### Modpack Version

1.5.0

### Describe your issue.

This happens when opening a backpack any way, (hotkey, item, block) with the error:

`Failed to open a screen with advanced data: java.lang.NullPointerException: Cannot invoke "net.p3pp3rf1y.sophisticatedcore.client.gui.StorageScreenBase.getMenu()" because "this.storageScreen" is null`

This error can also be seen in the latest.log.

Restarting the game did not fix it.

### Crash Report

N/A

### Latest Log

https://gist.github.com/moosetwin0/945ee1a47c1f5b4329d7907a806f3217

### Have you modified the modpack?

No

### User Modifications

N/A

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

N/A

**Comment by SubordinalBlue** [comment]
Got a crash report file? I find those easier to read.

**Comment by moosetwin0** [comment]
The game didn't crash, so I don't have a crash report file.

**Comment by moosetwin0** [comment]
Going to the curseforge page and having it repair the installation seems to have fixed this issue, I don't know why this fixed it.

(I intended to post this an hour ago, but it didn't go through and I only noticed that now)

**Comment by SubordinalBlue** [comment]
Glad to hear it's fixed. Enjoy your game!

**Comment by LucidLethargy** [comment]
We just encountered this issue on our 1.6.1 server as well.
