### ISSUE TITLE
[Bug Report]: Game crash on start

### ISSUE THREAD

**Issue by silicondallas** [TeamAOF/Craftoria#220]
### Modpack Version

1.5.0

### Describe your issue.

Crash of the game when trying to launch a modpack

### Crash Report

https://gist.github.com/silicondallas/2ab335bb12c5013443d4a3e30b85a3e8

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

### Discord Username

silicondallas

**Comment by SubordinalBlue** [comment]
Gotta give us the full crash-report or log... but even from that micro-snippet, my money is on wrong java version. It needs to be Java21.
