### ISSUE TITLE
[Bug Report]: Can't put lantern as wall fixtures

### ISSUE THREAD

**Issue by flubbychubby** [TeamAOF/Craftoria#229]
### Modpack Version

1.5.0

### Describe your issue.

I can put lanterns on blocks that act as floors but not on blocks that act as walls, if that makes sense

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by Linguardium** [comment]
lanterns cannot be hung on walls. That is a vanilla limitation.

**Comment by DiggityMan420** [comment]
the quark mod for example adds hanging lanterns witch is mot in the pack

**Comment by flubbychubby** [comment]
oh I see.. my bad thanks all
