### ISSUE TITLE
[Bug Report]: crash on launch after updating to 1.5

### ISSUE THREAD

**Issue by iT4ish** [TeamAOF/Craftoria#230]
### Modpack Version

1.5

### Describe your issue.

game crash on launch after updating to 1.5
went back to 1.4.1 and it work like a charm
tried to install the modpack again in a new profile still the same thing
and no crash log has been generated 

### Crash Report

none generated 

### Latest Log

https://gist.github.com/iT4ish/2d5fa278b05236c6eec24d69850bc134

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by SubordinalBlue** [comment]
Got a crash report, not a log, from that 1.5.0 launch?
Certainly sounds like an update that went wrong; official servers and the players on them have gone through all updates since 1.0 without crashes _from_ the updating.

**Comment by Linguardium** [comment]
This just looks like another failed curseforge update. I suggest using the repair option in the curseforge launcher or update to a new profile (also in the curseforge launcher)

**Comment by iT4ish** [comment]
> Got a crash report, not a log, from that 1.5.0 launch? Certainly sounds like an update process that went wrong; official servers and the players on them have gone through all updates since 1.0 without crashes _from_ the updating.

yes that log from the 1.5 
and ive tried reinstalling multiable times at this point 1.4.1 and lower all work fine for me but 1.5 always crash with the log above

**Comment by iT4ish** [comment]
i'll try reinstalling curse forge hope it works

**Comment by SubordinalBlue** [comment]
A "crash-report" is a different thing, not a log. I find them more succinct and easier to grok. Should be in the 'crash-reports' folder of a crashed instance.

**Comment by iT4ish** [comment]
> A "crash-report" is a different thing, not a log. I find them more succinct and easier to grok. Should be in the 'crash-reports' folder of a crashed instance.

i havent played modded minecraft for ages but i still remember that i used them to identify issues but in this case non is generated the whole folder isnt there there only the logs folder

**Comment by SubordinalBlue** [comment]
Not even a 'pid' file? Huh.

**Comment by iT4ish** [comment]
![Uploading image_2024-10-21_025742908.png…]()

**Comment by iT4ish** [comment]
for some reason changing the modding folder to another drive worked thx everybody for your time
