### ISSUE TITLE
[Bug Report]: crash when try to craft framed drawer 2x2

### ISSUE THREAD

**Issue by cychadopi** [TeamAOF/Craftoria#236]
### Modpack Version

1.5.0

### Describe your issue.

Game crashes when i try to crat a framed drawer 2x2 using a 2x2 drawer (dark oak) and two iron nuggets. The crash message says that the index is out of range (4 instead of 3). Tried three times with the same result. No report is produced sadly.
![Minecraft crash](https://github.com/user-attachments/assets/51d83439-5c88-49f5-bb4b-d5ef21d6adc6)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

cychadopi

**Comment by SubordinalBlue** [comment]
Need the actual crash report, please. (see the buttons in that modal dialog box you screen shotted)

**Comment by SubordinalBlue** [comment]
It’s right there in your screen shot… the button in the lower right.

**Comment by cychadopi** [comment]
I know i clicked on it and it says no bug report was produced. I can't do anything about it.

**Comment by SubordinalBlue** [comment]
Open the instance's folder. There could be a "pid" named file, or a "crash-reports" folder, or, at the least, a "logs" folder.

**Comment by Linguardium** [comment]
Mod bug. Seems to be fixed in development.  https://github.com/Buuz135/FunctionalStorage/issues/322

**Comment by Kazuhiko-Gushiken** [comment]
must be fixed by now, reopen if needed
