### ISSUE TITLE
[Bug Report]: 

### ISSUE THREAD

**Issue by Syrynicall** [TeamAOF/Craftoria#245]
### Modpack Version

1.5.0

### Describe your issue.

I have a hud on the side of my screen that I cant get rid of
![image_2024-10-26_231505789](https://github.com/user-attachments/assets/25a1d862-66e4-48cd-a22f-a8515a77ed1c)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

Wuinn_winn

**Comment by 800020h** [comment]
you pinned something in you quest book
artifacts and trinkets page

**Comment by Kazuhiko-Gushiken** [comment]
close
