### ISSUE TITLE
[Bug Report]: Server pack isn't a server pack

### ISSUE THREAD

**Issue by silasclockwork** [TeamAOF/Craftoria#246]
### Modpack Version

1.6.1

### Describe your issue.

The server pack you offer doesn't include the necessary files for a server pack. It's missing any and all mods or configs for this pack, requiring the user to sift through all the mods in the client pack and delete any client only mods, and if you miss even one, the server you're building manually will crash. This leads to an inconsistent gaming experience and has definitely so far made it confusing to whether it's the pack that's unstable. You will find that most packs that take the time to offer a server pack include all of the files for it, as well as many server side only improvements. I like the idea of this pack, but this has made it very difficult for me to recommend it to others.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by ImAK9** [comment]
I highly recommend running the startserver.bat/sh script shipped

**Comment by TheInfamousAlk** [comment]
I also have this issue. Please just include all of the mods, config and other files like all the other popular modpacks. Check out all the mods 10's implementation for a good example. https://www.curseforge.com/minecraft/modpacks/all-the-mods-10/files/5849656/additional-files

**Comment by TheInfamousAlk** [comment]
Why was this closed?

**Comment by SubordinalBlue** [comment]
The op closed it—presumably they tried the straightforward advice and considered the matter resolved.
The core of your post should really be its own suggestion issue, though its supporting argument is anchored with a false assumption. Aping ATM10 is not a motivation for Craftoria.

**Comment by silasclockwork** [comment]
Blue is basically correct. I embarrassed myself by not understanding a new thing I'd never come across. When I saw only a start batch file, I didn't realize that it had scripting built in to install the mods and configs itself as well and just assumed it was an omission. 

The comment suggesting I revisit the batch files made me come to that realization and I immediately closed it out of embarrassment.

**Comment by SubordinalBlue** [comment]
No need to feel embarrassed; we all encounter new stuff daily—probably a bad sign when we don't.

Cheers, enjoy your world(s)!

:heart-in-minecart:

**Comment by TheInfamousAlk** [comment]
> The core of your post should really be its own suggestion issue, though its supporting argument is anchored with a false assumption. Aping ATM10 is not a motivation for Craftoria.

"Aping ATM10" is not part of my supporting argument, I was just including that if you wanted to take a look at some server files to see what I mean, as I am not always great at explaining things. It just so happens that many other modpacks do the same thing, however. Because it's a good idea, not because they're all copying each other. When I said "like all the other popular modpacks" I did not mean it should be done _because_ everyone else does it, just that it should be done on its own merit, which is why it's such a popular practice in the first place. 

I will create a separate issue though, thank you for the suggestion.
