### ISSUE TITLE
KubeJS model and texture overrides question

### ISSUE THREAD

**Issue by sine707** [TeamAOF/Craftoria#259]
I really like the model and texture changes in some of the mods, particularly Modern Industrialization and Pipez.
Is there any info who made them and if one would be allowed to use them in their own modpacks?
Any plans to turn them into a resource pack?

**Comment by Nephrium** [comment]
The pipez one already has a resource pack. It's called Pretty Pipez. Not Pretty Pipes with an s, but Pretty Pipez with a Z. There is also a mekanism version that makes the Pipez mod pipes look better with mekanism.

**Comment by Kazuhiko-Gushiken** [comment]
@sine707 what Nephrium said with the Pipez textures is correct. The Modern Industrialization textures are custom made in house and are licensed under ARR for the time being.

**Comment by Kazuhiko-Gushiken** [comment]
closing. reopen if needed
