### ISSUE TITLE
[Bug Report]: Stack sizes are very screwed up.

### ISSUE THREAD

**Issue by Devintrainer** [TeamAOF/Craftoria#270]
### Modpack Version

1.6.1

### Describe your issue.

While in survival mode (but not creative mode), stack sizes are bugged as heck. Take dirt for example. One time, I tested with a stack of 64 dirt, and when it was in the hotbar, it read as over 128. And yes, I was able to place it all down as if it was that number I forgot rather than as if it was 64 dirt blocks. Another time, the number stayed at 64, but on the inventory screen, it displayed as 32 dirt. If I place one down, the inventory screen displays as 31. But when I click with a dirt block in my hand without placing it down, the inventory number resets to 32. Going back to creative mode presumably removes all of the dirt I had paced and picked back up, as the numbe rthen is 35. As evidenced by my two examples being different, the bug is inconsistent between play sessions. My golden carrots, supposed to be 64, are inflated to 123. And arrows are also affected by this bug, but in a different way. When I fire from a full stack of 64 arrows, the stack in my inventory gets halved to 32. After firing for a second time, the stack is reduced to 31, and stays that number. I've tried it both with and without the Infinity enchantment. I thought this bug was because of my sohisticated backpack's netherite stack upgrade, but unequipping it and removing the upgrade seems to have done nothing to this bug.

### Latest Log

https://mclo.gs/yfAR7Vt

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

kikhatadevin

**Comment by Mari023** [comment]
you likely have ae2wtlib's restock mode enabled.
It tries to keep the items in your hotbar at half a stack, filling (or emptying) it from the me system.
It shows the number in your hotbar as the number of items actually in the slot + the number o that item in the me system.
it disables itself in creative mode.

you can disable it in the wireless crafting terminal or using the `Restock` keybind

**Comment by Devintrainer** [comment]
> you likely have ae2wtlib's restock mode enabled. It tries to keep the items in your hotbar at half a stack, filling (or emptying) it from the me system. It shows the number in your hotbar as the number of items actually in the slot + the number o that item in the me system. it disables itself in creative mode.
> 
> you can disable it in the wireless crafting terminal or using the `Restock` keybind

That was the exact solution to my "issue". I feel really stupid now.
