### ISSUE TITLE
[Bug Report]: Modern Industrialization machine blocks get destroyed by Just Dire Things pickaxes

### ISSUE THREAD

**Issue by dulphin127** [TeamAOF/Craftoria#276]
### Modpack Version

1.6.1

### Describe your issue.

I broke a couple machines (eg. Electric Mixer, Steel Wiremill) with a Blazegold Pickaxe. 
And nothing dropped when they were broken.

Other pickaxes (eg. Diamond) work fine for mining these machines.

Looking at the machine blocks while holding a Blazegold pickaxe, Jade indicates that it can be broken with the pickaxe. (It displays with a green checkmark in the Jade overlay.)

We tried with all the other Just Dire Things pickaxes, and they also don't drop anything for the machines.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

dulphin127#9948

**Comment by cpbr-dev** [comment]
Might be related to this :
https://github.com/Direwolf20-MC/JustDireThings/issues/275

**Comment by Kazuhiko-Gushiken** [comment]
Like a 90% chance it's related to that.

**Comment by WhitePhant0m** [comment]
Fixed
