### ISSUE TITLE
[Bug Report]: Browncoat Zombies

### ISSUE THREAD

**Issue by ckocyigit** [TeamAOF/Craftoria#278]
### Modpack Version

1.7.0

### Describe your issue.

We are being overwhelmed by Browncoat Zombies continuously respawning in our base. Although our base is fully illuminated, they keep spawning in large numbers.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by ckocyigit** [comment]
I temporarily fixed it for myself with

```
const BANNED_MOBS = [
  'cnc:browncoat',
  'cnc:imp'
]

EntityEvents.spawned(event => {
    if (BANNED_MOBS.includes(event.entity.type)) {
        event.cancel();
    }
});
```

**Comment by James103** [comment]
I found the source of this issue; these two mobs are specifically coded within the mod to ignore light levels when checking to see if they can spawn. See also https://github.com/LopyLuna/Crops-n-Corpse/issues/55.

Does the Mega Torch from Torchmaster block spawns of these two zombie types from Crops and Corpses?

**Comment by Itskillerluc** [comment]
Yes i am fixing this

**Comment by Itskillerluc** [comment]
https://www.curseforge.com/minecraft/mc-mods/crops-n-corpses/files/5891516 it has been fixed here

**Comment by WhitePhant0m** [comment]
Mod was removed.
