### ISSUE TITLE
[Bug Report]: Break Factory Block 

### ISSUE THREAD

**Issue by Azertload** [TeamAOF/Craftoria#279]
### Modpack Version

1.7.0

### Describe your issue.

Hello,
I can't break any model of factory block.
Can you fix this bug?
Thank you
![2024-11-10_12 57 52](https://github.com/user-attachments/assets/23aba50b-411d-4aa9-a35a-1939c34cd597)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

Azerload

**Comment by gpoussel** [comment]
Hello,

This bug is reported on Factory Blocks mod: https://github.com/matthewperiut/factory_blocks/issues/12

**Comment by Kazuhiko-Gushiken** [comment]
and has been fixed since
