### ISSUE TITLE
[Bug Report]: Can't craft multiple Croptopia recipes including Cheese and Flour

### ISSUE THREAD

**Issue by GonB42** [TeamAOF/Craftoria#281]
### Modpack Version

1.7.0

### Describe your issue.

Was not able to craft either cheese or flour, went into the discord found out from a user named Linguardium states that the flourable tag appears empty.  Was suggested to submit a bug report
![cheese](https://github.com/user-attachments/assets/8a377b0a-9e14-48ba-b389-147eb1455b39)
![flour](https://github.com/user-attachments/assets/ad9e49ac-9c3d-4309-9c03-1860350f862a)
<img width="344" alt="tag" src="https://github.com/user-attachments/assets/fcb47785-0b35-4f16-8309-4062e6b24e1f">

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by Linguardium** [comment]
be sure to report it to the croptopia issue tracker as well https://github.com/ExcessiveAmountsOfZombies/Croptopia/issues

**Comment by WhitePhant0m** [comment]
Croptopia has been removed.
