### ISSUE TITLE
[Bug Report]: Modular Routers NBT data reset when unloaded

### ISSUE THREAD

**Issue by GamingEinstein** [TeamAOF/Craftoria#282]
### Modpack Version

1.7.1

### Describe your issue.

Modular Routers will reset their NBT data reset once the chunk is unloaded. This happens whether the chunk is claimed or not. It will, however, keep the modules if the chunk is force-loaded. My first comment below has a link to the error that occurs when it happens.

**Replicating the issue:**
1. Place a Modular Router
2. Install any amount of modules into it
3. Unload the chunk (changing dimensions and going far away gets the job done)
4. Return and inspect

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by James103** [comment]
Is the entire block deleted, or the module inventory/NBT data simply reset? What do you get in the client and server logs when the modular router block gets deleted / reset?

**Comment by GamingEinstein** [comment]
Wrote it wrong. I meant to say that the modules get deleted from the block.
But upon further checking, it looks like that the block itself gets reset (I turned eco mode on and when I tested, it turned back off), and checking the logs supports that (https://mclo.gs/QckIrbC).

**Comment by LeadAssimilator** [comment]
see https://github.com/MatyrobbrtMods/ModernIndustrialRouters/pull/1

**Comment by LeadAssimilator** [comment]
The router config will never save with MIR 2.0.0 so all modules will be lost and breaking the block will lead to a client crash (/fill command works however).

Depending how long an official fix takes to be published, you may want to release an updated pack with MIR removed.

**Comment by Matyrobbrt** [comment]
This bug should be fixed in MIR version 2.0.1 (pending CF approval). Thanks to @LeadAssimilator for the help.

**Comment by Matyrobbrt** [comment]
The file is approved, you can download it from https://legacy.curseforge.com/minecraft/mc-mods/modern-industrial-routers/files/5893382 until Craftoria is updated.

**Comment by LeadAssimilator** [comment]
@ImAK9 Can we get this fix rolled into 1.7.2?
