### ISSUE TITLE
[Bug Report]: Modular Routers modules disappearing

### ISSUE THREAD

**Issue by MCLady** [TeamAOF/Craftoria#290]
### Modpack Version

1.7.2

### Describe your issue.

Module in modular routers keep disappearing, I have replaced them several times, they will work but then just disappear. Chunks are loaded.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

MCLady

**Comment by Linguardium** [comment]
have you broken and re-placed the router? there was a change in the latest version that changes how owner ids are set for them.

post your latest.log

**Comment by WhitePhant0m** [comment]
Fixed in 1.8.0

**Comment by WhitePhant0m** [comment]
Wait no, maybe not, might've been thinking of another issue. Though, I haven't encountered it myself so far in either 1.8.0 or 1.9.0, so it's most likely fixed, re-open if you encounter it again, and logs would be nice.
