### ISSUE TITLE
[Bug Report]: Client crash on official NA 1.8.0 server when pressing FindMe keybind (default Y) while hovering mouse over an item

### ISSUE THREAD

**Issue by trunksbomb** [TeamAOF/Craftoria#294]
### Modpack Version

1.8.0

### Describe your issue.

1. Open your inventory
2. Hover over any item in inventory then press `y` (or whatever your keybind for FindMe is, I suppose)
3. Observe client crash

The issue is mitigated if you change the keybind to something you won't hit by accident or while typing in EMI search bar. Of course this just moves the issue to a different key.

Couldn't replicate on single player or single player open to LAN

Submitted to FindMe issue tracker also: https://github.com/Buuz135/FindMe/issues/47

### Crash Report

https://mclo.gs/MRyeLDn

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

trunksbomb

**Comment by Linguardium** [comment]
Tested a fresh server install on a fresh client install and had no issues.

tested in creative mode as well and the mod worked properly with no crash.  

Can you post the server latest.log from that crash?

**Comment by trunksbomb** [comment]
One of the server admins may opt to post it, I don't have access. AK is one of them, he's tagged by default here but he can possibly tag in another admin to get the log.

**Comment by trunksbomb** [comment]
Issue is resolved - server was missing the mod altogether. Pressing the FindMe keybind does not crash my client now.
