### ISSUE TITLE
[Bug Report]: Website "documentation" is lacking and mistaken in some parts

### ISSUE THREAD

**Issue by arfizato** [TeamAOF/Craftoria#297]
### Modpack Version

1.7.1+

### Describe your issue.

- Website claiming aether and twilight mods are installed on 1.7.1 when it's not the case
- download page downloads craftoria 1.6.1 not the latest version 
- no documentation or even links mods wikis

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by ImAK9** [comment]
We have no website and never have, this site ur talking about is AI generated and not by us. I'd close it immediately.

**Comment by arfizato** [comment]
Closed, but if the owner is really unknown they might be spreading malware in through the downloadable modpack. https://craftoria.net/download/
