### ISSUE TITLE
[Bug Report]: Server Installing Crash

### ISSUE THREAD

**Issue by jagile5** [TeamAOF/Craftoria#298]
### Modpack Version

1.8.0

### Describe your issue.

Installing the server, mods download fine but crashes when it gets to additionals:

The server installed successfully
You can delete this installer file now if you wish
[17:28:38] [INFO] Done installing loader, deleting installer!
[17:28:38] [INFO] Starting to installing Additional Files
[17:28:38] [INFO] Starting to copy local files.
[17:28:38] [INFO] Starting Loader, output incoming
Error: Could not find or load main class @libraries.net.neoforged.neoforge.21.1.77.win_args.txt
[17:28:39] [INFO] Server has been stopped, it has started 1 times in 60min

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

squash#1765

**Comment by Linguardium** [comment]
you are using the wrong java version. you require java 21 to be the default java install or you need to set your java21 file in the forced java path setting in the yaml

**Comment by Parvizall** [comment]
I need some help with that, can anyone show me their yaml file?

**Comment by Linguardium** [comment]
https://github.com/TeamAOF/Craftoria/blob/def92d058736d5681e8424e20cf801ab59f13361/server_files/server-setup-config.yaml#L67

This line should point to your java.exe file.
example:
`forcedJavaPath: C:\Program Files\Java\21\bin\java.exe`
