### ISSUE TITLE
[Bug Report]: MI cutting machine & Mekanism sawmill does not process modded wood types

### ISSUE THREAD

**Issue by James103** [TeamAOF/Craftoria#303]
### Modpack Version

1.8.0

### Describe your issue.

The Modern Industrialization cutting machine and the Precision Sawmill from Mekanism do not process logs if the species of the log is not one of the species in the vanilla game. For example, Spruce Logs can be broken down into 6 planks using either machine, but Aspen Logs can't. This causes vanilla logs to yield up to 50% more planks compared to modded logs, or equivalently makes building wooden structures with non-vanilla wood types to be 33% more expensive in terms of logs required.

Fixing this will require compatibility scripts or mods which find crafting recipes turning wood logs into planks and copy them to the MI cutting machine and Mekanism sawmill as appropriate.

### Have you modified the modpack?

Yes

### User Modifications

Base: Craftoria 1.8.0 (updated from 1.6.1)
Remove: Champions Unofficial (to reduce difficulty)
Remove: Crops 'n' Corpses (natural spawning of its mobs can't be blocked)
Add: No Chat Reports 1.21.1-v1.29.0
Add: Xaero's Minimap 24.6.1 and Xaero's World Map 1.39.0
Add: Tom's Simple Storage Mod 2.0.10

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by Kazuhiko-Gushiken** [comment]
should be fixed now
https://github.com/TeamAOF/Craftoria/commit/e0ebe7857dadfddce2fcb4051e17c5e0d41539fb
https://github.com/TeamAOF/Craftoria/commit/d9267ff984b64393a80a2423705e707fde5892e2
