### ISSUE TITLE
Не могу отключить какие-то зеленые, оранжевые и красные квадраты над блоками 

### ISSUE THREAD

**Issue by Pipotyg** [TeamAOF/Craftoria#306]
![17320286675327256510048675595514](https://github.com/user-attachments/assets/dfd38e41-66b1-4ed3-92a1-d9a7d85a233c)

**Comment by James103** [comment]
Running the title through Google Translate outputs this:
> I can't turn off some green, orange and red squares above the blocks

**Comment by Lusiphar** [comment]
It's some of F buttons. Maybe F6 - F7 - F8 i can't remember which one.

**Comment by James103** [comment]
It's caused by a mod which adds the Lighty Mode, which is responsible for the overlay. Use F7 to bring up the Lighty Mode menu, and F8 to toggle the overlay.

**Comment by Kazuhiko-Gushiken** [comment]
james got ya
