### ISSUE TITLE
[Bug Report]: Celestigem Paxel Recipe

### ISSUE THREAD

**Issue by aefyb** [TeamAOF/Craftoria#308]
### Modpack Version

1.8.0

### Describe your issue.

Recipe is to create celestigem paxel is missing, but is required for a quest.

### Have you modified the modpack?

Yes

### User Modifications

Added mostly QoL mods: [Xaero's minimap](https://www.curseforge.com/minecraft/mc-mods/xaeros-minimap), [Xaero's world map](https://www.curseforge.com/minecraft/mc-mods/xaeros-world-map), [open parties and claims](https://www.curseforge.com/minecraft/mc-mods/open-parties-and-claims), [easy piglins](https://www.curseforge.com/minecraft/mc-mods/easy-piglins), [easy villagers](https://www.curseforge.com/minecraft/mc-mods/easy-villagers), and [carry on](https://www.curseforge.com/minecraft/mc-mods/carry-on). The first three are just because I prefer Xaero's maps over FTBchunks. Also added a [resource pack](https://www.curseforge.com/minecraft/texture-packs/icons-xaero-minimap-x-fresh-animations) for xaero's minimap icons.

### Did the issue happen in singleplayer or on a server?

Server

**Comment by ThicoModee** [comment]
The recipe exists, you just need to combine the pickaxe, axe, and shovel in a smithing table (with a certain order). Same goes for other items like dry rubber and pink slime, the recipes still exist, they just arent displayed on emi.
