### ISSUE TITLE
[Bug Report]: no mods in zip folder

### ISSUE THREAD

**Issue by potato1king** [TeamAOF/Craftoria#320]
### Modpack Version

1.8

### Describe your issue.

no files in the mods folder of the modpack

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by Linguardium** [comment]
not an issue.

client zip file is a modpack. a launcher supporting modpacks must be used. https://prismlauncher.org/ for example

server zip file contains the startserver script for downloading and running the modpack.

**Comment by Kazuhiko-Gushiken** [comment]
What Ling said.
