### ISSUE TITLE
[Bug Report]: Pause Screen is invisible

### ISSUE THREAD

**Issue by payphone101** [TeamAOF/Craftoria#321]
### Modpack Version

1.9.0

### Describe your issue.

Pausing the game while in a world fails to show the buttons. They will still work when clicked on the right places, but the UI elements are not there. 
![image](https://github.com/user-attachments/assets/d36a0335-7055-47cd-9de1-51fdd38df685)

### Crash Report

No crash

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by James103** [comment]
Have you tried turning off the Menu Background Blur from the accessibility settings?
You may need to save and quit / disconnect then access the options menu from the title screen. If that doesn't work, you may need to close the client completely, then set `menuBackgroundBlurriness:0` in `options.txt` for the instance, then relaunch the client.

**Comment by payphone101** [comment]
yep that fixed it
