### ISSUE TITLE
[Bug Report]: Client hang when picking up an item for the first time

### ISSUE THREAD

**Issue by James103** [TeamAOF/Craftoria#323]
### Modpack Version

1.9.0

### Describe your issue.

When picking up an item for the first time after restarting a Craftoria client, the client hangs for around 5 seconds, all of which is spent rebuilding the item tabs/groups normally used in Creative Mode. This occurs even in Survival mode because the Loot Journal mod triggers the rebuild, not opening the Creative inventory.

Approximately half of that time is spent in Log Begone filtering out log messages produced during the creative inventory tab rebuild. See the attached spark profile for more information.

A similar hang occurs when using Inventory Profiles Next's middle-click functionality to sort a container or when going into Creative Mode and opening the Creative Mode inventory; if either of those occur first, picking up an item does not cause an additional hang.

### Spark profiles
Picking up an item: [10fmfVR6GP.zip](https://github.com/user-attachments/files/18069674/10fmfVR6GP.zip)

Sorting a container with Inventory Profiles Next: [X1UsC4P4k0.zip](https://github.com/user-attachments/files/18121889/X1UsC4P4k0.zip)

### Have you modified the modpack?

Yes

### User Modifications

Remove: Champions Unofficial (to reduce difficulty)
Add: No Chat Reports 1.21.1-v1.29.1
Add: Xaero's Minimap 24.6.1 and Xaero's World Map 1.39.0
Add: Tom's Simple Storage Mod 2.0.10

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by Gronglegrowth** [comment]
Oh is _that_ why?

**Comment by SubordinalBlue** [comment]
Great find/diagnosis ~~... but shouldn't this be a bug report with Loot Journal?

**Comment by SubordinalBlue** [comment]
Well... did you report the bug to them?

Unless I'm misunderstanding (always a good change of that), the only action available to the pack on this is to remove Loot Journal... which doesn't seem like the optimal outcome.

**Comment by MechanicalDragon0687** [comment]
Does this issue occur if you sort a chest with inventory profiles next in creative mode sort order (default) before picking up an item?

**Comment by James103** [comment]
> Does this issue occur if you sort a chest with inventory profiles next in creative mode sort order (default) before picking up an item?

Yes, the same hang occurs and the attached profiler results show the creative tab content rebuild being triggered by Inventory Profiles Next's item sorting function.
https://spark.lucko.me/X1UsC4P4k0
[X1UsC4P4k0.zip](https://github.com/user-attachments/files/18121889/X1UsC4P4k0.zip)

**Comment by MechanicalDragon0687** [comment]
> > Does this issue occur if you sort a chest with inventory profiles next in creative mode sort order (default) before picking up an item?
> 
> Yes, the same hang occurs and the attached profiler results show the creative tab content rebuild being triggered by Inventory Profiles Next's item sorting function. https://spark.lucko.me/X1UsC4P4k0 [X1UsC4P4k0.zip](https://github.com/user-attachments/files/18121889/X1UsC4P4k0.zip)

but does the item pickup lag happen after IPN has forced the creative tab groups to generate by using it to sort?
open container
sort
check if first pickup still lags

**Comment by James103** [comment]
> check if first pickup still lags

I do not get any additional lag upon picking up an item for the first time, if the creative tabs were already generated by usage of Inventory Profiles Next's sort function or opening the inventory in Creative Mode.

**Comment by MechanicalDragon0687** [comment]
Someone might be able to make a mod that generates those tabs at join, then, to put the lag up-front during loading

**Comment by IanTapply22** [comment]
@ImAK9 I'd call this as resolved as per the version 1.10.0 release changelog notes🙂. Can this be marked as resolved?
