### ISSUE TITLE
[Bug Report]:  Drygmy spawn

### ISSUE THREAD

**Issue by 45A7heid** [TeamAOF/Craftoria#327]
### Modpack Version

1.9.0

### Describe your issue.

Drygmy do not spawn naturally

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by Kazuhiko-Gushiken** [comment]
@45A7heid I'm going to need more evidence than "trust me bro." I just quickly flew around a 1.9.0 world in singleplayer and ran into a Drygmy within about a minute.
