### ISSUE TITLE
[Bug Report]: Can't get Iron's Spells trophy

### ISSUE THREAD

**Issue by alienghosts** [TeamAOF/Craftoria#329]
### Modpack Version

1.9.0

### Describe your issue.

I've completed Iron's Spells quest chapter before the bug with incorrect Completionist dependencies was fixed and now I still can't get the trophy. Could you please suggest maybe a console command to either complete the quest or reset it? Clicking the checkmark as usual doesn't do anything.

![image](https://github.com/user-attachments/assets/5a4dfffd-490b-4062-96d0-a5cb84226100)
![image](https://github.com/user-attachments/assets/31529d93-9787-44bf-a335-f34aac3e5e45)
![image](https://github.com/user-attachments/assets/88331fe7-e5c8-4a70-8f3f-7775fc781a7b)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by Kazuhiko-Gushiken** [comment]
if it happened before, if you're able to op yourself and just force complete that final quest. could be a bug within FTBQ where updating amidst a buggy dependency doesnt fix in the update.

**Comment by alienghosts** [comment]
Thanks! How do I `/give` myself the Iron's Trophy in that case? I've looked for something from `trofers`, but I only see pillars and can't find a way to give custom trophies
