### ISSUE TITLE
Idea: Antimatter Ingots and Antimatter Blocks

### ISSUE THREAD

**Issue by James103** [TeamAOF/Craftoria#331]
### Describe your suggestion

There should be Antimatter Ingots and Antimatter Blocks, which can be crafted to/from Antimatter Pellets the same way Iron Ingots/Blocks can be crafted to/from Iron Nuggets. 1 Antimatter Block = 9 Antimatter Ingots = 81 Antimatter Pellets.

### Why would you like this added/changed?

This enables Antimatter to be stored in a more compact way. Furthermore, these compressed variants of Antimatter can be ingredients for end-game crafts in place of larger numbers of Antimatter Pellets.

**Comment by Kazuhiko-Gushiken** [comment]
Antimatter pellets from Mekanism are very slow to produce. Plus at that point, making a supermassive QIO drive is very cheap and can store plenty of them.

I also don't think we'd do anything using Mek's antimatter for end-game crafts. It's just too cliche and bland of an end-game crafting material.

**Comment by James103** [comment]
Closing for that reason (as I don't think it will be implemented in the base Craftoria modpack). Maybe in an addon...
