### ISSUE TITLE
[Mod Suggestion]: Chipped Express

### ISSUE THREAD

**Issue by OcaLL-SmiLLe** [TeamAOF/Craftoria#335]
### URL

https://www.curseforge.com/minecraft/mc-mods/chipped-express/files/all?page=1&pageSize=20

### Why would you like this mod added?

This mod is the only way to automate Chipped blocks in a mass. It's really hard to make thousands of em for a big project to build. Chipped has a lot of good looking designs but the fact that you can't make them in a mass makes me avoid them.

**Comment by WhitePhant0m** [comment]
Implemented in 20b6a3b
