### ISSUE TITLE
[Bug Report]: after swapping from creative, no blocks drop when mining

### ISSUE THREAD

**Issue by neonjoe262** [TeamAOF/Craftoria#343]
### Modpack Version

1.21.1

### Describe your issue.

i gave myself creative mode, and when i swapped back to survival, i stopped getting anything i mined, its treating me as still being in creative i assume. i have tried using the server console to force myself into and out of game modes and giving and taking away admin privileges, and nothing is working.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

theolympian4169

**Comment by Linguardium** [comment]
are you using anything from JustDireThings?
if not, are you using a paxel?

**Comment by neonjoe262** [comment]
> are you using anything from JustDireThings? if not, are you using a paxel?

i was just using normal minecraft tools, and my hands if thats what you mean.

**Comment by neonjoe262** [comment]
even when i drop anything it instantly gets deleted. but other players are unaffected.

**Comment by neonjoe262** [comment]
completely ignore this. apparently i picked up a advanced magnetic upgrade for my backpack and it somehow equipped itself causing everything to instantly go into my backpack. there is no issue. just somehow equipped that item without even knowing how i had one. sorry for the alarm if i caused any.
