### ISSUE TITLE
[Bug Report]: Server installation

### ISSUE THREAD

**Issue by 3lias4** [TeamAOF/Craftoria#6]
### Modpack Version

0.0.7

### Describe your issue.

Hi, I tried to install the modpack on my server, but sadly it doesn't work properly. I downloaded the Server Modpack and launched it. After accepting the eula and installation of some files the server crashes and shows some errors in the console. I would be glad to get some help.

### Latest Log

https://gist.github.com/3lias4/7f409f765dda56e26d437d769684f654

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by ImAK9** [comment]
NF dosent support Java 22 as of now. Try Java 21

**Comment by ImAK9** [comment]
Reopen if still needing help
