### ISSUE TITLE
Unable to install server files.  

### ISSUE THREAD

**Issue by eractnod** [TeamAOF/Craftoria#68]
### Modpack Version

0.5.0

### Describe your issue.

When installing the server files, it makes it to The server installed successfully, but after Starting loader, output incoming get a boot layer error and it stops.  Not sure if this is a library issue or other.  I have tried deleting serverstarter.lock file and installing again, same error.  Deleted everything and downloaded the install file again.  Same error.

You have accepted the EULA.
[18:07:29] [INFO] Starting to installing Additional Files
[18:07:29] [INFO] Starting to copy local files.
[18:07:29] [INFO] Starting Loader, output incoming
Error occurred during initialization of boot layer
java.lang.module.FindException: Error reading module: libraries\cpw\mods\securejarhandler\3.0.8\securejarhandler-3.0.8.jar
Caused by: java.lang.module.InvalidModuleDescriptorException: Unsupported major.minor version 65.0
[18:07:29] [INFO] Server has been stopped, it has started 1 times in 60min

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by SubordinalBlue** [comment]
Wrong Java version perhaps?

**Comment by eractnod** [comment]
Was running Java 17.  Updated to 22, got a little farther, but still failed.  Have 18 loaded now with same error.
openjdk version "18.0.2" 2022-07-19
OpenJDK Runtime Environment (build 18.0.2+9-61)
OpenJDK 64-Bit Server VM (build 18.0.2+9-61, mixed mode, sharing)

INFO: Found 64-bit Java

**Comment by ImAK9** [comment]
You need Java 21

**Comment by eractnod** [comment]
Looks like 21 worked.  Thank you.
