### ISSUE TITLE
[Bug Report]: Archwood quest doesn't complete

### ISSUE THREAD

**Issue by Bookking2** [TeamAOF/Craftoria#71]
### Modpack Version

0.6.1

### Describe your issue.

Archwood quest in the Ars Nouveau tab isn't marked as completed even when archwood logs are in the inventory. Looks like tags in the quest filter and tags assigned to the logs are different.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by WhitePhant0m** [comment]
Fixed in 0.7.0
