### ISSUE TITLE
[Bug Report]: Modern Industrialization Sound Addon - Crashes the Server

### ISSUE THREAD

**Issue by RevLaw** [TeamAOF/Craftoria#75]
### Modpack Version

0.6.1

### Describe your issue.

Hey,
The server crashes when using the "Modern Industrialization Sound Add-on" mod. After removing this add-on, the server starts without issues. The crash occurs specifically when the "Steel Alloy Smelter" machine from the "Modern Industrialization" is running.

Thanks for the Pack :)

### Crash Report

https://gist.github.com/RevLaw/047f61c6cd900abbc71509195d487527

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

slpylaw

**Comment by WhitePhant0m** [comment]
You can fix it for now by updating tesseract API to 1.2.2+
the mod will be updated in the next pack update.
