### ISSUE TITLE
[Bug Report]: Game crashes after trying to search something in the inventory

### ISSUE THREAD

**Issue by Bookking2** [TeamAOF/Craftoria#79]
### Modpack Version

0.7.0

### Describe your issue.

On creative world game crashes after trying to search something in the inventory search.

### Crash Report

https://gist.github.com/Bookking2/b4d4b59a9ea824b8d67dd67a8e47bd5a

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by quinn-semele** [comment]
Already PR'd a fix to the mod developer, just need to wait for them to update.
https://github.com/henkelmax/easy-villagers/pull/228
