### ISSUE TITLE
Crashes on entering/leaving the nether

### ISSUE THREAD

**Issue by Seegras** [TeamAOF/Craftoria#8]
### Modpack Version

0.0.9

### Describe your issue.

hangs/crashes with "ticking player" on entering/leaving the nether. 

### Crash Report

https://gist.github.com/Seegras/de33885c22d936f0e88a5cbaf15da841

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by Seegras** [comment]
You still can visit the nether, you just need to kill/restart minecraft every time you change the dimension.

**Comment by ImAK9** [comment]
fixed in pack version 0.0.10
