### ISSUE TITLE
[Bug Report]: Applied Energistics 2 Pattern Crash

### ISSUE THREAD

**Issue by CATXVII** [TeamAOF/Craftoria#80]
### Modpack Version

0.7.0

### Describe your issue.

Crafted a pattern for the steel rod recipe and said item crashes my save without fail. tossing it on the ground and burning it does save me from a crash.

### Crash Report

https://gist.github.com/CATXVII/88a06f679cafe30a5f933281baa612bc

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

catxvii

**Comment by ImAK9** [comment]
For now if you're able to, downgrade IF to 1.2.18

**Comment by CATXVII** [comment]
Thank you for the response. Your sugestion did the trick. I am enjoying the pack at the moment, the questbook is semi bugged, especially the new chapter. Maybe its only on my side but the tanks from the Ore Multiplication chapter of mekanism are not getting picked up. Thank you again! Have a great morning/evening!

**Comment by SubordinalBlue** [comment]
Would you mind opening a new issue for that, for tracking purposes?

**Comment by WhitePhant0m** [comment]
Fixed in 0.8.0
