### ISSUE TITLE
[Bug Report]: Tank-of-Substance quests in Mekanism Ore Proc. chapter not completing.

### ISSUE THREAD

**Issue by SubordinalBlue** [TeamAOF/Craftoria#81]
Really just so I don't forget to figure this one out:

Worked fine when testing in development, after working out how to stop a tank with anything in it from completing multiple tank-involving quests.

### Did the issue happen in singleplayer or on a server?: Server, for me, testing production just now. Not sure about another player's report of same.

**Comment by ImAK9** [comment]
Fixed in 1.0.0
