### ISSUE TITLE
[Bug Report]: Crash with Spawners

### ISSUE THREAD

**Issue by xX4FingasXx** [TeamAOF/Craftoria#92]
### Modpack Version

0.8.0

### Describe your issue.

Having a consistent and repeatable crash when trying to view stats on collected spawners in inventory. Pressing shift while moused over causes an instant crash. Spawners with vanilla and modded mobs both effected. Hope this helps! 

### Crash Report

<script src="https://gist.github.com/xX4FingasXx/d81e8705dd8953d9c78a891878f7f18a.js"></script>

### Have you modified the modpack?

Yes

### User Modifications

I have extended the length of the seasons in the Serene Seasons mod, other than that not at all.

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

xX4FingasXx

**Comment by WhitePhant0m** [comment]
Update to 0.9.0(or better, wait for 0.9.1 to be approved on CF), fixed in those versions.
