### ISSUE TITLE
[Bug Report]: Server Crash - 

### ISSUE THREAD

**Issue by NoLiver92** [TeamAOF/Craftoria#93]
### Modpack Version

0.9.1

### Describe your issue.

We are just building and exploring in the world and the server keeps crashing, it appears mostly to happen at night with mobs spawning (attached crash log)

### Crash Report

https://gist.github.com/NoLiver92/573df366ba8e47f5c4c2852ab9c9f310

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

NoLiver#6125

**Comment by NoLiver92** [comment]
I have experienced some more errors with the skillet, this is the console output:

`[Server thread/ERROR] [minecraft/LevelChunk]: A BlockEntity type vectorwing.farmersdelight.common.block.entity.SkilletBlockEntity has thrown an exception trying to write state. It will not persist, Report this to the mod author
java.lang.IllegalStateException: Cannot encode empty ItemStack
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.item.ItemStack.save(ItemStack.java:409) ~[server-1.21.1-20240808.144430-srg.jar%23369!/:?] `

This seems to be similar to the server crashes

![image](https://github.com/user-attachments/assets/c127a6e5-81ca-4098-9888-791c1ee2ecdc)
A user crashed when interracting with this skillet 

![image](https://github.com/user-attachments/assets/641470bd-b49d-4bf5-8a5b-9b56e83a5ec2)
the same user didint crash when interracting with this skillet

**Comment by NoLiver92** [comment]
Appologies was trying to give an update, ive had more errors related to the skillet, this time though a player interraceted with one and caused a similar error but only they crashed not the server bit i believe they are related:

`[Server thread/ERROR] [minecraft/LevelChunk]: A BlockEntity type vectorwing.farmersdelight.common.block.entity.SkilletBlockEntity has thrown an exception trying to write state. It will not persist, Report this to the mod author
java.lang.IllegalStateException: Cannot encode empty ItemStack
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.item.ItemStack.save(ItemStack.java:409) ~[server-1.21.1-20240808.144430-srg.jar%23369!/:?] `

This skillet they crashed when interracting with:
![image](https://github.com/user-attachments/assets/d676e728-3f17-456e-9528-9ab423a3ab6c)

This skillet they could intteract with without crashing:
![image](https://github.com/user-attachments/assets/cf8f072e-819e-4b17-acbc-5aee7e0cea12)

**Comment by ImAK9** [comment]
Hmm, I’ll have a look into this. Thanks for reporting!

**Comment by ImAK9** [comment]
Reopen if still an issue
