### ISSUE TITLE
[Bug Report]: Mekanism: Ore Processing Quest Not Finishing

### ISSUE THREAD

**Issue by ChimeraGaming** [TeamAOF/Craftoria#95]
### Modpack Version

0.9.2

### Describe your issue.

Water (path to 1:3)
it does not recognize as completed, I have a full tank, an empty tank, a tank in bucket mode, a tank filled by buckets, a tank filled by a pump....
None are recognized as completed.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by SubordinalBlue** [comment]
Yep, my bad. I've gotta find a different solution for the water and gas / fluid tasks... FTBQ isn't playing nice. TY for the reminder!

**Comment by ChimeraGaming** [comment]
Can you add checkmarks for now?

**Comment by SubordinalBlue** [comment]
Already addressed in PR #96.
Pack updates typically wait one more significant changes and fixes than this to accrue before going out.

**Comment by ChimeraGaming** [comment]
So the next updates would most likely be with mod updates?

**Comment by SubordinalBlue** [comment]
Yes, and new mods too—the pack is still pre-1.0 after all.

**Comment by ImAK9** [comment]
Fixed in 1.0.0
