### ISSUE TITLE
[Bug Report]: Ticking block entity

### ISSUE THREAD

**Issue by NoLiver92** [TeamAOF/Craftoria#97]
### Modpack Version

0.9.1

### Describe your issue.

Someone on the server started working with ars nouveau storage (im not exactly sure what was placed down) and whenever someone spawns in near it, it crashes the server and the user. Other users can join the server but if they go near the area then they crash.

Ive tried to go near to find out what the item is but i crash and the only way to get back in is to edit the player data to move them away.

Ive attached the crash report.

### Crash Report

<script src="https://gist.github.com/NoLiver92/d054abf511081b8c6c094fc5f9f8dae0.js"></script>

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

NoLiver#6125

**Comment by Leonxilofin** [comment]
Its ars_nouveau:storage_lectern located at (15,144,-308). If you want to remove it you could try adding https://www.curseforge.com/minecraft/mc-mods/neruina/files/all?page=1&pageSize=20&version=1.21  to avoid crashing when getting close enough to remove. Although neruina is on 1.21 and not 1.21.1 so not 100% sure if that will work. But it is an option anyway

**Comment by NoLiver92** [comment]
Thank you for getting back to me, I had just found it was the storage lecturn and was about to give an update. I downloaded the world and used a map editor to delete the lecturn. i tried the mod but it didnt work for me, kept crashing the server still

**Comment by SubordinalBlue** [comment]
I've found one can often get close enough in world, just outside render distance, to use WorldEdit to remove problem blocks like that. For a server, that's more straight forward than copying and editing the appropriate region file, and restarting the server to replace it smoothly.

**Comment by ImAK9** [comment]
Reopen if still an issue
